# Configuration Nixpacks pour Railway
[phases.setup]
nixPkgs = ["php81", "nginx"]

[phases.build]
cmds = [
  "echo 'upload_max_filesize=10M' > custom-php.ini",
  "echo 'post_max_size=10M' >> custom-php.ini",
  "echo 'max_execution_time=120' >> custom-php.ini",
  "echo 'memory_limit=256M' >> custom-php.ini"
]

[start]
cmd = "php server.php"
