# Configuration Nixpacks pour Railway
[phases.setup]
nixPkgs = ["php81", "nginx"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "php -d upload_max_filesize=10M -d post_max_size=10M -d max_execution_time=120 -d memory_limit=256M -S 0.0.0.0:${PORT:-8000}"
